"""Writes docs/BRIEFING.md: a short analyst memo generated from the real-data results, so every number is reproducible.

Run:  PYTHONPATH=src python -m partd.briefing
"""
from __future__ import annotations

from . import config
from . import public_cms as P


def build() -> str:
    d = P.build_data()
    k, ins = P.kpis(d)
    nat = d["natl"].set_index("year")
    s = d["states"]
    hi, lo = s.iloc[0], s.iloc[-1]
    hi2 = s.iloc[1]
    n = d["negotiation"]
    glp = k["glp1_2024"]
    lines = [
        "# Part D cost trend briefing (real CMS public data)",
        "",
        "Generated by `python -m partd.briefing`. Gross cost before rebates, all of Medicare Part D. Not any one plan's data.",
        "",
        "## Bottom line",
        f"Gross Part D cost per member per month rose from ${k['pmpm_2020']:,.0f} (2020) to ${k['pmpm_2024']:,.0f} (2024), "
        f"then went flat from 2023 to 2024. Total spending reached ${k['spend_2024']/1e9:,.0f}B in 2024. "
        "The flat year hides two opposite forces: more claims per member and a drop in cost per claim, led by insulin list-price cuts.",
        "",
        "## What I would tell leadership",
        f"1. **Cost per claim, not volume, drove 2020 to 2023.** Claims per member barely moved ({nat.loc[2020,'claims_per_1000_mm']:,.0f} to {nat.loc[2023,'claims_per_1000_mm']:,.0f} per 1,000 member months); spend per claim went from ${nat.loc[2020,'spend_per_claim']:,.0f} to ${nat.loc[2023,'spend_per_claim']:,.0f}.",
        f"2. **2024 was an exception.** Spend per claim fell to ${nat.loc[2024,'spend_per_claim']:,.0f}. Insulin explains about $8B of a $29B negative price effect; the remainder is spread across ~2,700 drugs and not yet explained.",
        f"3. **GLP-1 drugs are the growth story.** ${k['glp1_2020']/1e9:,.1f}B to ${glp/1e9:,.1f}B between 2020 and 2024 ({glp/k['spend_2024']:.1%} of spend).",
        f"4. **2026 is a reset for ten drugs.** They were ${k['neg_spend']/1e9:,.0f}B ({k['neg_share']:.0%}) of 2024 spend. Applying the announced cuts to 2024 volume removes about ${k['neg_implied']/1e9:,.0f}B at list-price level. Early Q1 2026 data shows spend per claim already {-n['observed_change_per_claim'].max():.0%} to {-n['observed_change_per_claim'].min():.0%} lower for most of them.",
        f"5. **Geography matters.** Excluding DC (distorted by cross-border prescribing), {hi2['state']} is highest at ${hi2['gross_pmpm']:,.0f} and {lo['state']} lowest at ${lo['gross_pmpm']:,.0f} per member per month, a {hi2['gross_pmpm']/lo['gross_pmpm']:.1f}x spread. The data cannot say whether that is use, price, drug mix or plan mix.",
        "",
        "## What to watch",
        "- 2025 annual data when CMS publishes it; the preliminary quarterly figure ($351B) is not comparable to the annual series.",
        "- Whether the early drop in spend per claim for the negotiated drugs holds as Q2 2026 and later quarters arrive.",
        "- Mix of enrollment: MA-PD share rose from 47% to 57% of Part D enrollees between 2020 and 2024.",
        "",
        "## Caveats",
        "- Gross cost excludes rebates; net cost to a plan is lower and unknown here.",
        "- Dose units for injectables can change with strength and packaging, so unit-price movements for insulin and GLP-1 drugs are partly definitional.",
        "- State cost is by prescriber location; enrollment by member residence.",
        "- The 2026 price cuts are announced prices against list; the data check is directional.",
        "",
        "## Questions I would ask the team",
        "- Which of these views do you already produce, and which are rebuilt by hand each quarter?",
        "- How do you bridge gross to net in your own reporting, and which rebate assumptions are standard?",
        "- Which negotiated-drug effects are already in the 2026 bid versus still to come?",
        "",
        "## Reproduce",
        "`make public` downloads the CMS files and rebuilds the dashboard; `make excel` rebuilds the workbook; `make briefing` rebuilds this memo.",
    ]
    return "\n".join(lines) + "\n"


def run() -> str:
    out = config.ROOT / "docs" / "BRIEFING.md"
    out.write_text(build(), encoding="utf-8")
    print("wrote", out)
    return str(out)


if __name__ == "__main__":
    run()
