"""Writes docs/BRIEFING.md: a short analyst memo generated from the real-data results, so every number is reproducible.

Run:  PYTHONPATH=src python -m partd.briefing
"""
from __future__ import annotations

from . import config
from . import public_cms as P


def build() -> str:
    d = P.build_data()
    k, ins = P.kpis(d)
    nat = d["natl"].set_index("year")
    s = d["states"]
    hi, lo = s.iloc[0], s.iloc[-1]
    hi2 = s.iloc[1]
    n = d["negotiation"]
    glp = k["glp1_2024"]
    lines = [
        "# Medicare Part D Cost Trend: Briefing Memo",
        "",
        "Source: CMS public data (data.cms.gov). Figures are gross cost before rebates for all of Medicare Part D and do not represent any single plan. Generated by `python -m partd.briefing`.",
        "",
        "## Summary",
        f"Gross Part D cost per member per month rose from ${k['pmpm_2020']:,.0f} (2020) to ${k['pmpm_2024']:,.0f} (2024), "
        f"then was flat from 2023 to 2024. Total spending reached ${k['spend_2024']/1e9:,.0f}B in 2024. "
        "The flat 2024 result reflects two offsetting movements: higher claims per member and lower cost per claim, the latter led by insulin list-price reductions.",
        "",
        "## Key findings",
        f"1. **Cost per claim, not utilization, drove 2020 to 2023.** Claims per member barely moved ({nat.loc[2020,'claims_per_1000_mm']:,.0f} to {nat.loc[2023,'claims_per_1000_mm']:,.0f} per 1,000 member months); spend per claim went from ${nat.loc[2020,'spend_per_claim']:,.0f} to ${nat.loc[2023,'spend_per_claim']:,.0f}.",
        f"2. **2024 reversed the pattern.** Spend per claim fell to ${nat.loc[2024,'spend_per_claim']:,.0f}. Insulin accounts for about $8B of a $29B negative price effect; the remainder is spread across roughly 2,700 drugs and has not been attributed.",
        f"3. **GLP-1 drugs are the largest growth category.** ${k['glp1_2020']/1e9:,.1f}B to ${glp/1e9:,.1f}B between 2020 and 2024 ({glp/k['spend_2024']:.1%} of spend).",
        f"4. **Negotiated prices take effect in 2026 for ten drugs.** These drugs represented ${k['neg_spend']/1e9:,.0f}B ({k['neg_share']:.0%}) of 2024 spend. Applying the announced cuts to 2024 volume would reduce spend by about ${k['neg_implied']/1e9:,.0f}B at list-price level. Preliminary Q1 2026 data show spend per claim already {-n['observed_change_per_claim'].max():.0%} to {-n['observed_change_per_claim'].min():.0%} lower for most of these drugs.",
        f"5. **State-level variation is material.** Excluding DC (distorted by cross-border prescribing), {hi2['state']} is highest at ${hi2['gross_pmpm']:,.0f} and {lo['state']} lowest at ${lo['gross_pmpm']:,.0f} per member per month, a {hi2['gross_pmpm']/lo['gross_pmpm']:.1f}x spread. These data cannot distinguish utilization, price, drug mix or plan mix as the cause.",
        "",
        "## Recommended next steps and monitoring",
        "- Rebase the trend on the 2025 annual file when CMS publishes it; the preliminary quarterly figure ($351B) is not comparable to the annual series.",
        "- Confirm whether the early decline in spend per claim for the negotiated drugs persists as Q2 2026 and later quarters are released.",
        "- Enrollment mix: MA-PD share rose from 47% to 57% of Part D enrollees between 2020 and 2024.",
        "",
        "## Limitations",
        "- Gross cost excludes rebates; net cost to a plan is lower and cannot be determined from these data.",
        "- Dose units for injectables can change with strength and packaging, so unit-price movements for insulin and GLP-1 drugs partly reflect definitional changes.",
        "- State cost is by prescriber location; enrollment by member residence.",
        "- The 2026 reductions compare announced negotiated prices with list prices; the Q1 2026 check is directional only.",
        "",
        "## Open questions for the team",
        "- Which of these views are already produced, and which are rebuilt manually each quarter?",
        "- What gross-to-net bridge and rebate assumptions are standard in internal reporting?",
        "- Which negotiated-drug effects are already reflected in the 2026 bid?",
        "",
        "## Reproduce",
        "`make public` downloads the CMS files and rebuilds the dashboard; `make excel` rebuilds the workbook; `make briefing` rebuilds this memo.",
    ]
    return "\n".join(lines) + "\n"


def run() -> str:
    out = config.ROOT / "docs" / "BRIEFING.md"
    out.write_text(build(), encoding="utf-8")
    print("wrote", out)
    return str(out)


if __name__ == "__main__":
    run()
