"""Standalone HTML dashboard (no server needed): KPI tiles, auto-written insights, tabbed charts, data tables.

Run:  PYTHONPATH=src python -m partd.report   ->  reports/partd_dashboard.html
"""
from __future__ import annotations

import html

import pandas as pd
from plotly.offline import get_plotlyjs

from . import charts, config

TABS = [
    ("overview", "Overview", ["pmpm_vs_budget", "variance"]),
    ("drivers", "Trend drivers", ["waterfall_gross", "waterfall_net", "movers"]),
    ("benefit", "Benefit and members", ["who_pays", "cat", "top_drugs", "concentration"]),
    ("quality", "Data quality", ["edits", "completion"]),
]

CSS = """
:root{color-scheme:light;--bg:#f9f9f7;--surface:#fcfcfb;--ink:#0b0b0b;--ink2:#52514e;--muted:#898781;--line:#e1e0d9;--blue:#2a78d6}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}
header{padding:24px 16px 8px;max-width:1180px;margin:0 auto}h1{font-size:22px;margin:0 0 4px}header p{margin:0;color:var(--ink2)}
main{max-width:1180px;margin:0 auto;padding:0 16px 48px}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px;margin:16px 0}
.tile{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:12px 14px}
.tile .l{color:var(--ink2);font-size:13px}.tile .v{font-size:26px;font-weight:600}.tile .s{color:var(--muted);font-size:12px}
.insights{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:8px 18px;margin:8px 0 16px}
.insights li{margin:8px 0}
nav{display:flex;gap:4px;flex-wrap:wrap;border-bottom:1px solid var(--line);margin-bottom:16px}
nav button{background:none;border:0;padding:10px 14px;font:inherit;color:var(--ink2);cursor:pointer;border-bottom:2px solid transparent}
nav button[aria-selected=true]{color:var(--ink);border-color:var(--blue);font-weight:600}
section.panel{display:none}section.panel.on{display:block}
.card{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:8px;margin-bottom:16px}
details{margin:0 8px 8px}summary{cursor:pointer;color:var(--ink2);font-size:13px}
table{border-collapse:collapse;font-size:12px;margin-top:6px;display:block;max-height:260px;overflow:auto}
td,th{padding:3px 10px;border-bottom:1px solid var(--line);text-align:right;font-variant-numeric:tabular-nums}th{position:sticky;top:0;background:var(--surface)}
.method h3{margin:20px 0 4px}.method p,.method li{color:var(--ink2)}
.warn{border-left:3px solid #eda100;padding:6px 12px;background:var(--surface);margin:12px 0}
"""

JS = """
const btns=document.querySelectorAll('nav button');
function show(id){document.querySelectorAll('section.panel').forEach(p=>p.classList.toggle('on',p.id===id));
btns.forEach(b=>b.setAttribute('aria-selected',b.dataset.t===id));
window.dispatchEvent(new Event('resize'));}
btns.forEach(b=>b.onclick=()=>show(b.dataset.t));show('overview');
"""

METHOD = """
<div class="method">
<div class="warn"><b>Synthetic data.</b> All figures are generated by this repository. No data originates from UnitedHealth Group or any other plan. Benefit parameters are illustrative and should be verified against the CMS Rate Announcement before any production use.</div>
<h3>What the numbers mean</h3>
<ul>
<li><b>Net plan liability</b> = covered plan paid minus estimated CMS reinsurance on catastrophic gross cost. <b>PMPM</b> divides by member months.</li>
<li><b>Completion adjusted</b>: recent months are grossed up by a completion factor learned from mature months (IBNR). The latest month is the least certain.</li>
<li><b>Final action</b>: only the latest accepted record per claim counts; adjustments replace, deletions remove, rejected submissions are excluded and tracked.</li>
<li><b>Trend drivers</b>: year over year change split into utilization, mix and price with an exact-sum identity (tested).</li>
<li><b>Forecast</b>: fit on 2025 onward only (the benefit design changed). The method is chosen by rolling-origin backtest. The backtest contains few observations, so method selection and interval width are provisional.</li>
</ul>
<h3>Known simplifications</h3>
<ul>
<li>Deductible applies to all tiers; adjustments are generated only on plan-only claims; completion factor is gross-based and applied uniformly.</li>
<li>Budget is synthetic. 2027 is not modeled.</li>
<li>Benefit phase is re-derived from claim history, which is valid only when the history is complete.</li>
</ul>
</div>
"""


def _table(df: pd.DataFrame, n: int = 60) -> str:
    return df.head(n).to_html(index=False, border=0, float_format=lambda v: f"{v:,.2f}")


def build() -> str:
    d = charts.load_data()
    kpis, insights = charts.compute_kpis(d)
    k = kpis
    tiles = [
        ("FY projected net plan", f"${k['fy_projection']/1e6:.1f}M", f"budget ${k['fy_budget']/1e6:.1f}M"),
        ("FY variance to budget", f"{k['fy_variance_pct']:+.1%}", f"range {k['fy_variance_low']:+.1%} to {k['fy_variance_high']:+.1%}"),
        ("YTD net plan PMPM", f"${k['ytd_net_plan_pmpm']:,.0f}", f"budget ${k['ytd_budget_pmpm']:,.0f}"),
        ("Gross PMPM trend YoY", f"{k['gross_trend_pct']:+.1%}", "YTD, completed"),
        ("Catastrophic penetration", f"{k['cat_now']:.1%}", f"{k['cat_prior']:.1%} a year ago"),
        ("Unresolved rejects", f"${k['unresolved_dollars']/1e3:,.0f}K", "gross cost not in payment"),
    ]
    tile_html = "".join(f'<div class="tile"><div class="l">{a}</div><div class="v">{b}</div><div class="s">{c}</div></div>' for a, b, c in tiles)
    ins_html = "<ul>" + "".join(f"<li>{html.escape(i)}</li>" for i in insights) + "</ul>"

    first = True
    panels = []
    for tid, _, keys in TABS:
        cards = []
        for key in keys:
            fig = charts.ALL_FIGS[key](d)
            div = fig.to_html(full_html=False, include_plotlyjs=False, config={"displaylogo": False})
            data_rows = []
            for tr in fig.data:
                x = getattr(tr, "x", None)
                y = getattr(tr, "y", None)
                if x is not None and y is not None and len(x) == len(y):
                    data_rows.append(pd.DataFrame({"series": tr.name or "", "x": [str(v)[:10] for v in x], "y": list(y)}))
            tbl = _table(pd.concat(data_rows)) if data_rows else ""
            det = f"<details><summary>View data</summary>{tbl}</details>" if tbl else ""
            cards.append(f'<div class="card">{div}{det}</div>')
        panels.append(f'<section class="panel" id="{tid}">{"".join(cards)}</section>')
    panels.append(f'<section class="panel" id="method">{METHOD}</section>')

    nav = "".join(f'<button data-t="{t}" aria-selected="false">{n}</button>' for t, n, _ in TABS) + '<button data-t="method" aria-selected="false">Methodology</button>'
    return (
        f"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
        f"<title>Medicare Part D Cost Trend Analysis</title><style>{CSS}</style><script>{get_plotlyjs()}</script></head><body>"
        f"<header><h1>Medicare Part D Cost Trend Analysis</h1><p>Synthetic plan-level PDE data, extract as of {config.AS_OF_DATE}. Net plan liability, trend drivers, benefit phases and data quality.</p></header>"
        f"<main><div class='tiles'>{tile_html}</div><div class='insights'>{ins_html}</div><nav>{nav}</nav>{''.join(panels)}</main>"
        f"<script>{JS}</script></body></html>"
    )


def run() -> str:
    config.REPORT_DIR.mkdir(parents=True, exist_ok=True)
    out = config.REPORT_DIR / "partd_dashboard.html"
    out.write_text(build(), encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size/1e6:.1f} MB)")
    return str(out)


if __name__ == "__main__":
    run()
